### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by orlade** [thebignet/swagger-codegen-gradle-plugin#10]
When trying to include this plugin (v1.3 and v1.4) with Gradle 2.10 and Java 7 (1.7.0_80), I get the following error:

```
java.lang.UnsupportedClassVersionError: org/detoeuf/SwaggerCodeGenPlugin : Unsupported major.minor version 52.0
```

My understanding is that this means the plugin was built with an incompatible JDK, but a Gradle plugin should definitely be compatible with Java 7.

**Comment by thebignet** [comment]
There was no reason to require JDK8 for this plugin.  Therefore, I published fixed versions of versions 1.3 and 1.4 through version 1.3.1 and 1.4.1 respectively.
