### ISSUE TITLE
Configurable configPackage setting?

### ISSUE THREAD

**Issue by laszlomiklosik** [thebignet/swagger-codegen-gradle-plugin#12]
Hello, 

I am very happy to find this plugin!
Is there an easy way already to use a custom name for the _configPackage_?

I use your plugin to generate Spring MVC REST server-side stubs. Via command line this means:

`java -jar /swagger-codegen-cli-2.1.6.jar generate -i my_api.yaml -l spring-mvc -o ./my_server -c server-config.json`

Using this option I can specify the _configPackage_ using:

```
{
  "configPackage": generated.config",
  "apiPackage": "generated.api",
  "modelPackage": "generated.domain"
}
```

Another option is to pass it via command line JVM arg:

`java -jar /swagger-codegen-cli-2.1.6.jar generate -i my_api.yaml -l spring-mvc -o ./my_server -c server-config.json -DconfigPackage=my.config.package`

otherwise it uses the hardcoded package name: _io.swagger.configuration_

I tried passing the JVM arg via Gradle but that was not picked up.

Thanks!

**Comment by laszlomiklosik** [comment]
Thanks :) I was also ready to push the related change.

Can you please also deploy it to:  https://plugins.gradle.org/m2/gradle/plugin/org/detoeuf/swagger-codegen-plugin/1.5.0/swagger-codegen-plugin-1.5.0.jar

(I'd like to refer your version in my project)

**Comment by thebignet** [comment]
I'm currently having issues pushing to plugin portal.  I think it's coming from my network.  Will try with another one in a few hours.

**Comment by thebignet** [comment]
Plugin published

**Comment by laszlomiklosik** [comment]
thanks!
