### ISSUE TITLE
swaggerOutput vs. swaggerSrc option

### ISSUE THREAD

**Issue by laszlomiklosik** [thebignet/swagger-codegen-gradle-plugin#13]
What is the purpose of having 2 configurable options for the output directory?

I was getting the sources generated in 2 locations: under `src/swagger` and the directory I configured for _swaggerOutput_ while using `language=java` with this plugin.

In the plugin documentation I found:

> swaggerOutput - target output path (default is ${project.build.directory}/generated-sources/swagger)
> swaggerSrc - target source directory (default is ${project.root.directory}/src/swagger). This directory should be added as as source set

And in the sources I see:

```
    @TaskAction
    def swaggerCodeGen() {
       ...
        new DefaultGenerator().opts(input).generate()
        project.copy {
            from outputDir+'/src/main/'+project.swaggerLanguage
            into srcDir+'/'+project.swaggerLanguage
        }
    }
```

Is there any particular reason for copying the sources and not generating them directly in the location configured under _swaggerOutput_,  maybe a workaround to avoid the _java_ (swagger language name) from the generated path?

My workaround to the problem of sources being generated in 2 locations is now is that I configure _swaggerSrc_ only (thus leaving the default location for _swaggerOutput_) and just don't include the sources from the _swaggerOutput_ location. 

When using `language=spring-mvc` I did not have this problem while only configuring the _swaggerOutput_ option. This happens because the above Groovy  snippet does not find a source folder and thus the destination folder does not get created.

The plain library accepts a single parameter for the generation location and I think it would be most intuitive to have the same behavior from the plugin.

```
java -jar swagger-codegen-cli-2.1.6.jar generate -i my_api.yaml -l java -o ./my-api-client
```

which would naturally translate to `swaggerOutput=my-api-client`

My suggestion would be to remove the option _swaggerSrc_ and generate the code to the _swaggerOutput_  folder directly and then suggest users to add the `$swaggerOuput/src/main/java` folder as extra source set.

**Comment by thebignet** [comment]
Good point here.  At first design, _swaggerSrc_ was intended to be a destination sourceSet having production sources.  I agree that _swaggerOutput_ is sufficient for this plugin and that source copy can be added as an additional task if needed.  I'll make a change in this way.
