### ISSUE TITLE
swaggerInputSpec does not get resolved correctly in a multi build setup

### ISSUE THREAD

**Issue by Hendrik-H** [thebignet/swagger-codegen-gradle-plugin#14]
Hi,
when I specify the swaggerInputSpec as a relative path in a sub project and start the build from the root project then the path is not correctly resolved. The problem should be in line 19 of https://github.com/thebignet/swagger-codegen-gradle-plugin/blob/master/src/main/groovy/org/detoeuf/SwaggerCodeGenTask.groovy. The path should be resolved relative to project.projectDir (https://docs.gradle.org/current/dsl/org.gradle.api.Project.html#org.gradle.api.Project:projectDir).

**Comment by thebignet** [comment]
swaggerInputSpec is now used like other paths in configuration.  Can you check that everything is ok in your multi-module project and report here ?  Thanks

**Comment by Hendrik-H** [comment]
I tested with 1.5.1. Works fine now. Thanks for the quick fix!
