### ISSUE TITLE
Support serializableModel parameter

### ISSUE THREAD

**Issue by amdonov** [thebignet/swagger-codegen-gradle-plugin#15]
The latest swagger code generation supports a boolean parameter called serializableModel that causes the model  classes to implement the java.io.Serializable interface. Can you add support for that parameter or more generally support addition of new parameters?

**Comment by thebignet** [comment]
I'm currently aiming at a refactoring that will be able to pass swagger-codegen parameters more easily.  I'll keep up to date in this issue.

**Comment by thebignet** [comment]
Version 1.6.0 allows passing native swagger-codegen parameters.  This means that _serializableModel_ can be passed in the _additionalProperties_.  Can you give it a try ?
