### ISSUE TITLE
Deleting of files

### ISSUE THREAD

**Issue by Nightapes** [thebignet/swagger-codegen-gradle-plugin#16]
Hello,

i change files from the generated code and add it to the .swagger-codegen-ignore. When i run the plugin again, all changes are reset. I found that you delete [SwaggerCodeGenTask.groovy#L24](https://github.com/thebignet/swagger-codegen-gradle-plugin/blob/master/src/main/groovy/org/detoeuf/SwaggerCodeGenTask.groovy#L24.) the complete output folder. Is this necessary?

**Comment by thebignet** [comment]
Usually, the output folder would be a specific generated folder.  This is also to ensure that any deleted objects from the spec file will have the corresponding Java class correctly deleted.

**Comment by Nightapes** [comment]
Okay, is there a possibility to skip deleting the build files, like build.gradle, and so. So that the plugin only deletes the src folder.

**Comment by thebignet** [comment]
We could add a property say _cleanOutputDir_ or something like that.  It would be true by default.  I've updated to version 1.6.0 with new features and a new example.  It's primarily based at generating classes in a deletable/non-versionned folder, though.

Classes could also be generated one-shot in a src folder in the meantime and use source control to restore deleted files.

**Comment by Nightapes** [comment]
Yes sounds good, should i help and make a pull request?

**Comment by thebignet** [comment]
That would be great.  And that way, you could test it for your needs.
