### ISSUE TITLE
Generated classes fail to compile due to missing io.swagger.client.* dependency if swagger codegen isn't use in default sourceSet

### ISSUE THREAD

**Issue by childnode** [thebignet/swagger-codegen-gradle-plugin#18]
for a setup where swagger client and code gen is only used in test:

```
plugins {
    id 'java'
    id 'org.detoeuf.swagger-codegen' version '1.6.0'
}

ext {
    swaggerDir = "${project.buildDir.path}/generated-test-sources/swagger"
}

sourceSets {
    test {
        java {
            srcDir("${swaggerDir}/src/main/java")
        }
    }
}

dependencies {
    testCompile 'io.swagger:swagger-jersey2-jaxrs:1.5.9'
}

swagger {
    inputSpec = "${project.rootDir}/src/specialSourceSet/resources/swagger.yaml"

    output = swaggerDir
    language = 'java'

    additionalProperties = [
            'modelPackage'     : 'com.example.my.model',
            'apiPackage'       : 'com.example.my.api',
            'dateLibrary'      : 'java8',
            'library'          : 'jersey2'
    ]
    apis = ''
    models = ''
}
```

compilation fails due to hard-baken compile dependency but testCompile has no swagger client dependency, e.g.

`/my/projectdir/build/generated-test-sources/swagger/src/main/java/com/example/my/api/DefaultApi.java:4: error: package io.swagger.client does not exist
import io.swagger.client.ApiClient;`

referring to
https://github.com/thebignet/swagger-codegen-gradle-plugin/blob/master/src/main/groovy/org/detoeuf/SwaggerCodeGenPlugin.groovy#L12

I _tried_ this workaround:

```
dependencies {
    configurations {
        testCompile.extendsFrom swaggerCompile
        testRuntime.extendsFrom swaggerRuntime
    }
}

compileTestJava.dependsOn 'swagger'
```

but I can't cleanup compile dependency either ... 

```
## HACK; DIRT; PSEUDO_CODE
dependencies {
    configurations {
        compile.excludeAny swaggerCompile.dependencies
        runtime.excludeAny swaggerRuntime.dependencies
    }
}
## HACK; DIRT; PSEUDO_CODE
```

anyway ... not working at all ... I'm missing somewhat ... perhaps more ☕ helps .. 

🙏  would be nice to get this some more sourceSet specific. e.g. Avro plugin extends each sourceSet where a swagger file might be set in and auto-fetched for generating classes.
For swagger-codegen, the dependency should only be relevant for the given 

P:S:
sure, `swaggerCompile` is an implicit scope from your example sourceset "swagger" and is not predefined.
So, I can't see any code that will anyway solve this client dependency ... 😕 

---

https://github.com/thebignet/swagger-codegen-gradle-plugin/blob/master/src/main/groovy/org/detoeuf/SwaggerCodeGenPlugin.groovy#L15

^ should be updated anyway ... from 1.5.0 to 1.5.9

---

^^

`testCompile 'io.swagger:swagger-jersey2-jaxrs:1.5.9'`
will result in duplicated annotations dependency

🎁 if a known "library" is set, auto-add relevant dependency ,)

**Comment by thebignet** [comment]
Thanks for the detailed issue.  Have you tried the [example repository](https://github.com/thebignet/swagger-codegen-gradle-plugin-example) ?  The link in the README was incorrect and I've just put in the right one.

Also, swagger-annotations dependency should probably be externalized so plugin user could be able to update it manually.  I'll see what is possible for that.

**Comment by childnode** [comment]
hi,

nope, didn't saw the explicit [example repo](https://github.com/thebignet/swagger-codegen-gradle-plugin-example) but it doesn't differ from the example given in your Readme here ;)
so, the use case is not adressed in the example either.

I'm not that familiar with the different swagger component's yet, what exactly do you mean with

> swagger-annotations dependency should probably be externalized

and which implications are set by 

> user could be able to update it manually

regarding fixing missing dependencies?!

But for now, I will first start over with your exmple repo and my swagger file going forward to see where the root problem is ;)

so, perhaps, you might first point out for which use cases your gradle plugin is build for to see where edge or special cases come in?!

I'm coming back with some feedback after testing ... ~Marcel

**Comment by thebignet** [comment]
Thanks for the feedback @childnode.  I've externalized the swagger-annotations dependency, which means that you now have to declare it in your build file, but this means that you can choose which version to use.  See #20 and [example repo](https://github.com/thebignet/swagger-codegen-gradle-plugin-example) which has been updated for details

**Comment by childnode** [comment]
thx so far .. seems to be way better for customized setups, but I was running running into jersey2 problems:
I can into `WARNING: The following warnings have been detected: WARNING: HK2 failure has been detected in a code that does not run in an active Jersey Error scope.` followed / raised by `java.lang.NoClassDefFoundError: org/glassfish/jersey/server/internal/inject/AbstractHttpContextValueFactory`
exception:

to solve this, an additional dep for 
`'org.glassfish.jersey:jax-rs-ri:2.0-rc1'`
was needed:

a full example for Jersey2 with custom sourceSet:

```
plugins {
    id 'java'
    id 'org.detoeuf.swagger-codegen' version '1.6.1'
}

ext {
    swaggerDir = "${project.buildDir.path}/generated-test-sources/swagger"
}

sourceSets {
    swaggertest {
        java {
            srcDir("${swaggerDir}/src/main/java")
        }
        resources
        compileClasspath += sourceSets.test.runtimeClasspath
        runtimeClasspath += sourceSets.test.runtimeClasspath
    }
}

dependencies {

    swaggertestCompile 'io.swagger:swagger-jersey2-jaxrs:1.5.9'
    swaggertestCompile 'io.swagger:swagger-annotations:1.5.9'
    swaggertestRuntime 'org.glassfish.jersey:jax-rs-ri:2.0-rc1'

    configurations {
        swaggertestCompile.extendsFrom integrationtestCompile
        swaggertestRuntime.extendsFrom integrationtestRuntime
    }
}

swagger {
    inputSpec = "${project.rootDir}/src/ratpack/assets/swagger.yaml"

    output = project.ext.swaggerDir
    language = 'java'

    additionalProperties = [
            'modelPackage': 'com.example.my.model',
            'apiPackage'  : 'com.example.my.api',
            'dateLibrary' : 'java8',
            'library'     : 'jersey2'
    ]
    apis = ''
    models = ''
}
```

not yet validated 100% since I'm running into additional problems of the specific environment, but : thats not a swagger problem anymore ,)

So once again: thank you very much!

**Comment by thebignet** [comment]
You're welcome!
