### ISSUE TITLE
JAX-RS server stubs generation?

### ISSUE THREAD

**Issue by hrstoyanov** [thebignet/swagger-codegen-gradle-plugin#19]
How can I generate Java JAX-RS server stubs? The following does not work in this plugin, but I believe is the correct:

```
swagger {
    ...
    language = 'jaxrs-spec'
   ...
}
```

**Comment by thebignet** [comment]
Apparently, you need to use one of the following
- jaxrs-cxf
- jaxrs
- jaxrs-resteasy

in order to generate a server stub for JAX-RS.
