### ISSUE TITLE
Build dependency

### ISSUE THREAD

**Issue by bdpeterson** [thebignet/swagger-codegen-gradle-plugin#24]
I didn't expect that the 'build' task would run the swagger task.
This causes a problem since I am unable to consistently build the swagger target.
Is there a way to make this configurable? I am new to gradle plugins.

Within IntelliJ gradle plugin, my swagger target fails when using a local file for the 'inputSpec' however, if I use an http source for the 'inputSpec' it works.

Using gradle from the command line works fine either way.

**Comment by thebignet** [comment]
For your first problem, it is possible to exclude a task from execution like so
`gradle build -x swagger`

For the second problem, this really is an issue.  I'll look into it

**Comment by thebignet** [comment]
For the second problem, can you try using the file scheme (ie file://path/to/file) ?

**Comment by bdpeterson** [comment]
For the first issue, I knew about the -x but was surprised that your plugin defaulted to pre-build step.

On the second, I've tried what you suggested to no avail within IntelliJ. (Command line is fine)

Here is my json file for inputSpec
`{
  "swagger": "2.0",
  "info": {
    "description": "Api Documentation",
    "version": "1.0",
    "title": "Api Documentation",
    "termsOfService": "urn:tos",
    "contact": {},
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0"
    }
  },
  "host": "localhost:8080",
  "basePath": "/product-server",
  "tags": [{
    "name": "address-api-controller",
    "description": "the address API"
  }],
  "paths": {
    "/address{?city,state,zip}": {
      "get": {
        "tags": ["address-api-controller"],
        "summary": "getAddress",
        "description": "Validates a provided address.",
        "operationId": "getAddressUsingGET",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [{
          "name": "city",
          "in": "query",
          "description": "the city",
          "required": false,
          "type": "string"
        }, {
          "name": "state",
          "in": "query",
          "description": "the state",
          "required": false,
          "type": "string"
        }, {
          "name": "zip",
          "in": "query",
          "description": "the zip",
          "required": false,
          "type": "string"
        }],
        "responses": {
          "200": {
            "description": "The validated address.",
            "schema": {
              "$ref": "#/definitions/CityStateZip"
            }
          },
          "422": {
            "description": "The address is not valid.",
            "schema": {
              "$ref": "#/definitions/CityStateZip"
            }
          },
          "500": {
            "description": "500 message",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "securityDefinitions": {
    "tokenKey": {
      "type": "apiKey",
      "name": "tokenKey",
      "in": "header"
    }
  },
  "definitions": {
    "CityStateZip": {
      "type": "object",
      "properties": {
        "city": {
          "type": "string"
        },
        "preferred": {
          "type": "string"
        },
        "state": {
          "type": "string"
        },
        "zip": {
          "type": "string"
        }
      }
    }
  }
}`

**Comment by thebignet** [comment]
I've created an [example for this issue](https://github.com/thebignet/swagger-codegen-gradle-plugin-example/tree/issue24) using your swagger file.  Can you try this using `gradle clean swagger` ?

**Comment by bdpeterson** [comment]
I am sorry for the delay... I will test it in the next few days. (Got slammed)

**Comment by thebignet** [comment]
Did you manage to make it work @bdpeterson ?

**Comment by greg-stein** [comment]
Hi, this is a bit old, but I have relevant issue - I'm trying to configure my build.gradle so that when I build from Idea it does first swagger task.

So I added this:
```gradle
build.dependsOn swagger
```
This caused:
> org.gradle.api.internal.tasks.TaskDependencyResolveException: Could not determine the dependencies of task ':build'.

When I run 
> gradle swagger

everything works fine.

**Comment by thebignet** [comment]
Plugin behavior is to have `compileJava` depend on `swagger`.  This means that swagger generation has to happen before compilation.
