### ISSUE TITLE
Incomplete codegen for java + okhttp and java + retrofit2

### ISSUE THREAD

**Issue by albertonavarro** [thebignet/swagger-codegen-gradle-plugin#25]
The list could be longer, I don't really know if I'm doing something wrong with the plugin but it worked fine for spring.

When I use this plugin (1.6.2) with java and okhttp, I find it doesn't generate many of the classes that are generated using the tool directly, including APIClient class, needed at compile time. Similar with retrofit.

Is this something it's going to be fixed with 1.6.3?

my code (unfortunately I cannot share the swagger file)

> swagger {
>     inputSpec = "${buildDir}/swagger-files/account-service-api-${supported_api_version}.yaml"
> 
> ```
> output = 'build/swagger'
> language = 'java'
> 
> additionalProperties = [
>         'dateLibrary'      : 'java8',
>         'library' : 'okhttp-gson'
> ]
> apis = ''
> models = ''
> ```
> 
> }

I tried with and without api and domain packages, no difference.

Missing classes for okhttp.. APIClient, APIException, Pair... all of them generated one level above model package by the codegen tool. 

`[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/alberto/code/account-service/client/./src/main/java/io/swagger/client/ApiException.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/alberto/code/account-service/client/./src/main/java/io/swagger/client/Configuration.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/alberto/code/account-service/client/./src/main/java/io/swagger/client/Pair.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/alberto/code/account-service/client/./src/main/java/io/swagger/client/auth/Authentication.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/alberto/code/account-service/client/./src/main/java/io/swagger/client/ApiCallback.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/alberto/code/account-service/client/./src/main/java/io/swagger/client/ApiResponse.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/alberto/code/account-service/client/./src/main/java/io/swagger/client/JSON.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/alberto/code/account-service/client/./src/main/java/io/swagger/client/ProgressRequestBody.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/alberto/code/account-service/client/./src/main/java/io/swagger/client/ProgressResponseBody.java`

Other missing classes, the ones under auth

`[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/alberto/code/account-service/client/./src/main/java/io/swagger/client/ApiClient.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/alberto/code/account-service/client/./src/main/java/io/swagger/client/StringUtil.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/alberto/code/account-service/client/./src/main/java/io/swagger/client/auth/HttpBasicAuth.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/alberto/code/account-service/client/./src/main/java/io/swagger/client/auth/ApiKeyAuth.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/alberto/code/account-service/client/./src/main/java/io/swagger/client/auth/OAuth.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/alberto/code/account-service/client/./src/main/java/io/swagger/client/auth/OAuthFlow.java`

Hopefully you'll at least respond soon

Thanks

Alberto Navarro

**Comment by thebignet** [comment]
Hi Alberto,

I've published an example using okhttp-gson with java8 dates on [this repository](https://github.com/thebignet/swagger-codegen-gradle-plugin-example).  Generated code contains ApiClient, ApiException amongst others.

Can you try by cloning this example ?  You can replace inputSpec with your swagger file.

**Comment by albertonavarro** [comment]
Hi

It works, with both your file and mine, now I need to understand what I was
doing wrong.

Thanks a lot, for both your work, and for helping me

Alberto Navarro
