### ISSUE TITLE
Publish 1.6.3 to plugins.gradle.org

### ISSUE THREAD

**Issue by ChristianUlbrich** [thebignet/swagger-codegen-gradle-plugin#26]
Running the example code, I get the error:

```
Plugin [id: 'org.detoeuf.swagger-codegen', version: '1.6.3'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Gradle Central Plugin Repository (plugin 'org.detoeuf.swagger-codegen' has no version '1.6.3' - see https://plugins.gradle.org/plugin/org.detoeuf.swagger-codegen for available versions)
```

 Looking at https://plugins.gradle.org/plugin/org.detoeuf.swagger-codegen indeed the last version seems to be 1.6.2; but I need 1.6.3 for the fix #21 .

Could you please publish the new version or am I doing something wrong?

@srehlig FYI!

**Comment by thebignet** [comment]
No you are right.  I haven't published the version.  Version is now [published](https://plugins.gradle.org/plugin/org.detoeuf.swagger-codegen).

**Comment by blub0hr** [comment]
You're missing a release version on github tho.
