### ISSUE TITLE
[FeatureRequest] Support for missing CodeGen options like TypeMappings

### ISSUE THREAD

**Issue by childnode** [thebignet/swagger-codegen-gradle-plugin#27]
Would be great to discuss some enhancement like: Support For TypeMappings

Perhaps, it's easy to just add any options https://github.com/swagger-api/swagger-codegen/blob/v2.2.1/modules/swagger-codegen/src/main/java/io/swagger/codegen/config/CodegenConfigurator.java

what is inpossible for me atm:

```
    CodegenConfigurator configurator = new CodegenConfigurator()
    // ...
    configurator.setTypeMappings([
            "DateTime": "java.time.Instant"
    ])
    configurator.setImportMappings([
            "Instant": "java.time.Instant"
    ])
```

**Comment by thebignet** [comment]
Would you like to make a PR for this ?  It shouldn't be too difficult.  As I see, there should be an optional parameter typeMappings, which is a map to be given to method configurator.setTypeMappings

**Comment by childnode** [comment]
On my way. For King and Country. :dash:

**Comment by childnode** [comment]
a simple but more drastic way to solve this: https://github.com/thebignet/swagger-codegen-gradle-plugin/compare/master...childnode:feature/eliminateSwaggerPluginExtensionInFavourOfCodegenConfiguratorPassedToGradle?expand=1

I see: this would break any current usage ... so I'll go backward making it less radical but "backward compatible"

**Comment by childnode** [comment]
let's discuss 

is https://github.com/thebignet/swagger-codegen-gradle-plugin/compare/master...childnode:feature/27-addMissingConfiguratorOptions?expand=1
good enough for a pr?! :)

I see ... documentation is still incomplete, not checked safety for correctness, neither did I add any tests ... yet

**Comment by thebignet** [comment]
Sorry for the delay.  The PR has conflicts due to other PR merged in the meantime.  Do you think you could rebase this PR on master ?

**Comment by childnode** [comment]
seems to there is another pr #30 that merely covers `importMapping`
perhaps @boxever is willing to help getting rebased what has been discussed in https://github.com/thebignet/swagger-codegen-gradle-plugin/issues/27#issuecomment-249118738 where importMapping was covered too, see 
 	04ec440
\+	25021e6 => e.g. [README line 86](https://github.com/thebignet/swagger-codegen-gradle-plugin/commit/25021e664c6ee5586286dd0c2a1974f3f4523da2#diff-04c6e90faac2675aa89e2176d2eec7d8R86), [SwaggerCodeGenTask.groovy line 27](https://github.com/thebignet/swagger-codegen-gradle-plugin/commit/25021e664c6ee5586286dd0c2a1974f3f4523da2#diff-5e91e7f762c26d0a41377c8ccb1786efR27)
\+	5ecd050

but @boxever also thought on the test class {{SwaggerCodeGenTaskTest}} ... I didn't *\*shameOnMe\**

mhh ... let's see if I get all this together - if someone's faster ... feel free, but just let me know it you're working on ;)

**but** @thebignet the last entry on this discussion ended on the question mark if it's ok in general to go forward or if we would like a more drastic way as suggested in my first "draft" in  https://github.com/thebignet/swagger-codegen-gradle-plugin/issues/27#issuecomment-249109481
so: what do you think about these two approaches? Which one do you prefer?

**Comment by thebignet** [comment]
ImportMappings as well as other properties on [CodegenConfigurator](https://github.com/swagger-api/swagger-codegen/blob/v2.2.1/modules/swagger-codegen/src/main/java/io/swagger/codegen/config/CodegenConfigurator.java) can be used now.
