### ISSUE TITLE
Simple example (below chapter Usage) failes...

### ISSUE THREAD

**Issue by wwn** [thebignet/swagger-codegen-gradle-plugin#29]
... with
`Execution failed for task ':swagger'.

> Can't load config class with name spring-mvc
> `
> `Caused by: java.lang.RuntimeException: Can't load config class with name spring-mvc
>         at org.detoeuf.SwaggerCodeGenTask.forName(SwaggerCodeGenTask.groovy:54)
> `

Why?

**Comment by GustavoMunoz** [comment]
Same issue here. Any ideas?

**Comment by thebignet** [comment]
Have you tried to use spring-boot instead ?  I think that this is the new name used for the spring template.
