### ISSUE TITLE
Published location

### ISSUE THREAD

**Issue by RobMcA** [thebignet/swagger-codegen-gradle-plugin#33]
I'm writing a custom plugin and want to declare a runtime dependency on this library. Is it published anywhere? Maven Central has no record of it. I tried the following: 

```
dependencies {
  runtime "org.detoeuf:swagger-codegen-plugin:1.6.3"
}
```

**Comment by thebignet** [comment]
Apparently, it should be located at https://plugins.gradle.org/m2/.  Try to add this maven repository to your configuration.

**Comment by RobMcA** [comment]
So I tried the following configuration:

```
dependencies {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  // Swagger
  compile "org.detoeuf:swagger-codegen-plugin:1.6.3"
}
```

and got this result:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'amp-gradle-plugin'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not find org.detoeuf:swagger-codegen-plugin:1.6.3.
     Searched in the following locations:
         https://plugins.gradle.org/m2/org/detoeuf/swagger-codegen-plugin/1.6.3/swagger-codegen-plugin-1.6.3.pom
         https://plugins.gradle.org/m2/org/detoeuf/swagger-codegen-plugin/1.6.3/swagger-codegen-plugin-1.6.3.jar
     Required by:
         project :
```

But if I pull down the repo and do ```./gradlew install``` and add ```mavenLocal()``` to my dependency list, it resolves fine.

So perhaps publishing the plugin to https://plugins.gradle.org/m2 does not make the compilation unit available, and it can only be referenced as a plugin?

**Comment by RobMcA** [comment]
I think I've found it. When plugins are published to https://plugins.gradle.org/m2, their group name is prefixed with ```gradle.plugin```. So for resolving the compilation unit, you have to use ```gradle.plugin.org.detoeuf:swagger-codegen-plugin:1.6.3```.

You might want to publish the compilation unit on maven central and/or jcenter so other who want a compile-time dependency can reference the library.

**Comment by thebignet** [comment]
I think gradle plugins are only meant to be used inside a gradle build as a plugin rather than as a dependency.  Maybe that's partly why the plugins are stored under prefix gradle.plugin.  I think it should be kept this way.  This is also why it makes sense to keep this dependency on plugins.gradle.org
