### ISSUE TITLE
Multiple Tasks

### ISSUE THREAD

**Issue by sesslerp** [thebignet/swagger-codegen-gradle-plugin#34]
Is there a way to execute the swagger task multiple times with different configurations?

I'm migrating from a maven project where I used multliple execution blocks to generate spring boot server stubs as well as jersey2 client classes. Is there a way to achieve the same thing with this gradle plugin?

**Comment by JLLeitschuh** [comment]
The way that this plugin is structured I'm going to say no (an educated guess, I'm still learning gradle).
The way of getting around this it by creating separate projects and applying the plugin in those separate projects with different configuration.

Or you could not use this plugin and write it yourself with the same logic in this plugin but in the `buildSrc` project.
Then you could run the same task with multiple configurations.

Good luck!

**Comment by thebignet** [comment]
I agree with @JLLeitschuh.  Multiple projects seem to be the simplest way to achieve this.  You can use project hierarchy to avoid unnecessary boilerplate.
