### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by JLLeitschuh** [thebignet/swagger-codegen-gradle-plugin#35]
What is this project Licensed under?

**Comment by thebignet** [comment]
Hi, sorry for not keeping up to date with this repository.  I've added a GNU GPL v3.0 licence to this repository.  Feel free to fork it as well as publish plugins if you like.  If you would like to maintain this plugin, it can also be possible.

**Comment by JLLeitschuh** [comment]
GNU GPL v3.0 is a copyleft and I'm trying to use this software internally at my company.

I'll be moving on, thanks so much for your time.

**Comment by JLLeitschuh** [comment]
> The GNU Project has two principal licenses to use for libraries. One is the GNU Lesser GPL; the other is the ordinary GNU GPL. The choice of license makes a big difference: using the Lesser GPL permits use of the library in proprietary programs; **using the ordinary GPL for a library makes it available only for free programs.**

\- [Why you shouldn't use the Lesser GPL for your next library](https://www.gnu.org/philosophy/why-not-lgpl.html)

I disagree with the name on the title of the article but this is your library.
I just want to make sure that you know what your library is licensed under.

**Comment by thebignet** [comment]
Thank you @JLLeitschuh for your analysis.  I was really concerned about sharing modifications to this software.  Copyleft is a big issue, specifically for commercial software and I don't want to infringe on it.  I replaced the license with MIT which is the most permissive.  Again, if you'd like to fork this repo and make improvements, you're welcome to do so.  Try to be as generic as you can, so changes can be merged and that your software doesn't leak through to the plugin.

I also got some good information on [Choose an open source license](https://choosealicense.com/)

**Comment by JLLeitschuh** [comment]
This is much better, I can contribute my changes back now and use it as a library.
Thank you!

**Comment by thebignet** [comment]
You're welcome !
