### ISSUE TITLE
Pass swagger-codegen version as argument

### ISSUE THREAD

**Issue by dylan-colaco** [thebignet/swagger-codegen-gradle-plugin#37]
It would be great if we could pass in the version of swagger-codegen as an argument to the plugin.
We have problems with v2.2.1 and are still using v 2.1.6, but the gradle plugin is hard-coded to 2.2.1

**Comment by thebignet** [comment]
I  tried to add the swagger codegen version as a parameter, but the problem is that it is a compile dependency. I'll look into it further to see if there's a way to force it.

**Comment by thebignet** [comment]
Seems this is not possible as plugin requires a specific version to compile
