### ISSUE TITLE
Version 1.6.3 at the plugin repo doesn't match the example

### ISSUE THREAD

**Issue by dbyron0** [thebignet/swagger-codegen-gradle-plugin#38]
In my build.gradle i have:
```groovy
plugins {
    id 'org.detoeuf.swagger-codegen' version '1.6.3'
}
```
and then following the readme I have:
```groovy
swagger {
    output = 'build/swagger'
    lang = 'spring-mvc'
}
```
but I get this error:
```
A problem occurred evaluating root project 'cni_android_mdm'.
> Could not set unknown property 'outputDir' for object of type org.detoeuf.SwaggerPluginExtension.
```

If I change output to outputDir, and lang to language, the errors go away.

Perhaps related, I don't see a 1.6.3 tag in the git repo.

Thanks for your help.

-DB

**Comment by thebignet** [comment]
[Example](https://github.com/thebignet/swagger-codegen-gradle-plugin-example) is now in sync with plugin
