### ISSUE TITLE
Question about configuration (documentation issue?)

### ISSUE THREAD

**Issue by bradyhegberg** [thebignet/swagger-codegen-gradle-plugin#39]
It would be great to have some more examples of configuration.  In my case I'm getting properly generated files but I can't figure out how to get rid of the @ApiModelProperty annotations

For example:

```
   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

```

I also can't get verbose to work.

Thanks for any help.

**Comment by thebignet** [comment]
This plugin aims to bring the swagger-codegen-plugin to Gradle by calling the main CodeGen class from [swagger-codegen-maven-plugin](https://github.com/garethjevans/swagger-codegen-maven-plugin).  All configuration is taken from there.
