### ISSUE TITLE
ignoreFileOverride properties dont work for me

### ISSUE THREAD

**Issue by sytolk** [thebignet/swagger-codegen-gradle-plugin#45]
swager-codegen have ignoreFileOverride option to set file .swagger-codegen-ignore (Use this file to prevent files from being overwritten by the generator)

```gradle
swagger {
    inputSpec = 'http://localhost:8080/v1/swagger.json'

    outputDir = "${rootDir}/swagger-client"
    lang = 'java'

    additionalProperties = [
            'library'           : 'retrofit2',
            'useRxJava2'        : 'true',
            'useGzipFeature'    : 'true',
            'parcelableModel'   : 'true',
            'serializableModel' : 'true',
            'dateLibrary'       : 'java7',
            'ignoreFileOverride': "${projectDir}/.swagger-codegen-ignore"
    ]
}
```
If I add this all files are not modified

```gradle
tasks.getByName("swagger") {
    cleanOutputDir = false
}
```

Can I have .swagger-codegen-ignore ?

**Comment by thebignet** [comment]
Look at updated [example](https://github.com/thebignet/swagger-codegen-gradle-plugin-example) for writing a custom task, which you can use to `config.setIgnoreFileOverride(".swagger-codegen-ignore")`
