### ISSUE TITLE
Doesn't seem to create output files

### ISSUE THREAD

**Issue by gwynjudd** [thebignet/swagger-codegen-gradle-plugin#47]
I've got this in my build.gradle:

```
plugins {
    id 'org.detoeuf.swagger-codegen' version '1.7.1'
    id 'java'
}

swagger {
    inputSpec = 'http://localhost/revapi/swagger/docs/v2'

    outputDir = 'swagger-java-client'
    lang = 'java'
}
```

I run `gradle swagger`, and I expect that the directory "swagger-java-client" will be created and contain the generated client SDK. I can see the task run without error, and lots of output indicating that "stuff" is being created, but at the end, no output directory is created.

I'm probably doing something stupid, any help would be appreciated.

**Comment by gwynjudd** [comment]
The last few lines from the build output:

```
warning!  No inner type supplied for array parameter "columns", using String
warning!  No inner type supplied for array parameter "columns", using String
warning!  No inner type supplied for array parameter "columns", using String

BUILD SUCCESSFUL

Total time: 57.855 secs
```

**Comment by majestix508** [comment]
Same problem here - but without this warnings from @gwynjudd - I think they are not related to the swagger-codegen plugin.

**Comment by majestix508** [comment]
Ok I found out why there is no output. Run 'gradle swagger -d ' and you will see that the swagger-plugin creates the files somewhere outside the project directory (in my case c:/Users/myuser/.gradle/daemon/3.4/...)
I tried a couple of thins like 'outputDir: $buildDir/swagger' or 'outputDir: ./build/swagger' but always with the same result - now I'm using a absolute Path - maybe someone has a better idea?

**Comment by majestix508** [comment]
Ok this works for me:
```groovy
def swaggerOutputDir = "${buildDir}/swagger"

swagger {
    inputSpec = 'http://localhost:8080/myfancyrestendpoint/swagger.json'
    outputDir = swaggerOutputDir
    lang = 'csharp'
}
```
