### ISSUE TITLE
Generating models from multiple sources

### ISSUE THREAD

**Issue by steam0** [thebignet/swagger-codegen-gradle-plugin#52]
Hi,

I am trying to generate domain models from multiple services. I dont see how I can do that with this plugin? Can you tell me if this is possible and show me a basic example of how to do it?

Eksample: I want to get domain models from these three servers
localhost:8081 - Package name: com.github.server1
localhost:8082 - Package name: com.github.api.different.package
localhost:8083 - Package name: com.github.server3

Thanks in advance

**Comment by steam0** [comment]
Example: 

I want to run both these configurations in the same swagger generation run.

Api1

    swagger {
    inputSpec = 'http://localhost:8081/v2/api-docs'

    outputDir = 'build/generated-sources/apifromserver1'
    lang = 'spring'

    addDynamicProperty 'sourceFolder', ''

    additionalProperties = [
            'modelPackage': 'com.github.apifromserver1',
    ]

    systemProperties = [
            'models': ''
    ]
    }

Api2

    swagger {
    inputSpec = 'http://localhost:8082/v2/api-docs'

    outputDir = 'build/generated-sources/server2name
    lang = 'spring'

    addDynamicProperty 'sourceFolder', ''

    additionalProperties = [
            'modelPackage': 'com.github.server2name,
    ]

    systemProperties = [
            'models': ''
    ]
    }

**Comment by holmbech** [comment]
Hi,

I would like the same functionality.

steam0 did you come with a solution?

**Comment by steam0** [comment]
Yes, I did but not with this plugin. 

Take a look at this excellent guide: https://www.jcore.com/2017/05/22/automatically-generating-api-using-swagger-and-gradle/

I ended up creating a partly generic gradle task based on that example. I am on vacation now (answering from my phobe), but I think this is all you need. 

https://gist.github.com/steam0/4fa11ad0660d33192ec01cd84050f226

**Comment by holmbech** [comment]
Awesome! Just what I was looking after.

Thanks a lot! :-D

**Comment by thebignet** [comment]
This is great !  It would be even more flexible than a plugin as it would allow changing swagger-codegen version dynamically.  I'll keep it in mind !

**Comment by thebignet** [comment]
I've updated README and example with this.  Fixes a lot of issues people were having.  Thanks for the tip
