### ISSUE TITLE
Question regarding customised generator

### ISSUE THREAD

**Issue by zacyang** [thebignet/swagger-codegen-gradle-plugin#56]
Hi,
I have a forked swagger-codegen which is used inside my company. 

I wonder if it is possible to specify a the code generator to be my customised one, like the maven plugin does [swagger-code-gen maven plugin](https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen-maven-plugin#custom-generator) ?

Thanks.

**Comment by thebignet** [comment]
It should theoretically work by adding your custom generator to build script dependencies like so.

```
buildscript {
  dependencies {
    classpath group: 'my.group', name: 'custom-generator', version: '1.0.0'
  }
}
```

Can you try and report here ?

**Comment by zacyang** [comment]
I added the buildscript section as you suggested:
in gradle 3.3
```
buildscript {
    repositories {
        mavenLocal()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }

    dependencies {
        classpath "gradle.plugin.org.detoeuf:swagger-codegen-plugin:1.7.4"
        classpath "io.swagger:swagger-generator:2.2.3-SNAPSHOT"
    }
}
apply plugin: "org.detoeuf.swagger-codegen"
```
where io.swagger:swagger-generator:2.2.3-SNAPSHOT is the forked version of the original one. 

Result is , it picked up the master version of generator.

**Comment by thebignet** [comment]
Did you apply additionalProperty `language: com.my.package.for.GeneratorLanguage` ?  It would also probably be better to include this new generator in its own jar as suggested in the [documentation](https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen-maven-plugin#custom-generator).

**Comment by thebignet** [comment]
I've added an [example for writing a custom task](https://github.com/thebignet/swagger-codegen-gradle-plugin-example) for generating code with swagger.  This should allow you to use your custom dependency.
